[launcher]
author = Mondoo, Inc.
description = Splunk Technology Add-on for ingesting Mondoo audit, advisory, agent, asset, vulnerability and policy data via the Mondoo GraphQL API and file-based ETL exports.
version = 1.0.0

[ui]
is_visible = 1
label = Mondoo Log Ingestion

[id]
name = TA-mondoo
version = 1.0.0

[package]
id = TA-mondoo
check_for_updates = true

[install]
is_configured = 0
build = 1779293000
state = enabled
state_change_requires_restart = false
requires_splunk_version = 9.0.0
