# ---------------------------------------------------------------------------
# CIM tags. Tag-driven data model selection — see also eventtypes.conf.
# ---------------------------------------------------------------------------

[eventtype=mondoo_audit]
change = enabled
audit = enabled
report = enabled

[eventtype=mondoo_advisory]
vulnerability = enabled
report = enabled

[eventtype=mondoo_vulnerability]
vulnerability = enabled
report = enabled

[eventtype=mondoo_vulnerabilities]
vulnerability = enabled
report = enabled

[eventtype=mondoo_asset]
endpoint = enabled
inventory = enabled
asset = enabled
report = enabled

[eventtype=mondoo_agent]
endpoint = enabled
inventory = enabled
report = enabled

[eventtype=mondoo_check]
alert = enabled
report = enabled

[eventtype=mondoo_control]
report = enabled

[eventtype=mondoo_package]
inventory = enabled
report = enabled

[eventtype=mondoo_query]
report = enabled
