# ---------------------------------------------------------------------------
# Lookup table: map Mondoo action strings to CIM action values
# ---------------------------------------------------------------------------
[mondoo_action_lookup]
filename   = mondoo_action_map.csv
case_sensitive_match = false

[mondoo_asset]
SOURCE_KEY = MetaData:Source
DEST_KEY = MetaData:Sourcetype
REGEX = \-assets\.jsonl$
FORMAT = sourcetype::mondoo:json:asset

[mondoo_check]
SOURCE_KEY = MetaData:Source
DEST_KEY = MetaData:Sourcetype
REGEX = \-checks\.jsonl$
FORMAT = sourcetype::mondoo:json:check

[mondoo_control]
SOURCE_KEY = MetaData:Source
DEST_KEY = MetaData:Sourcetype
REGEX = \-controls\.jsonl$
FORMAT = sourcetype::mondoo:json:control

[mondoo_package]
SOURCE_KEY = MetaData:Source
DEST_KEY = MetaData:Sourcetype
REGEX = \-packages\.jsonl$
FORMAT = sourcetype::mondoo:json:package

[mondoo_query]
SOURCE_KEY = MetaData:Source
DEST_KEY = MetaData:Sourcetype
REGEX = \-queries\.jsonl$
FORMAT = sourcetype::mondoo:json:query

[mondoo_vuln]
SOURCE_KEY = MetaData:Source
DEST_KEY = MetaData:Sourcetype
REGEX = \-vuln\.jsonl$
FORMAT = sourcetype::mondoo:json:vuln