[expose:mondoo_input_data]
pattern = data/inputs/mondoo_input
methods = GET, POST

[expose:mondoo_input_data_specified]
pattern = data/inputs/mondoo_input/*
methods = GET, POST, DELETE

[expose:mondoo_input_data_action]
pattern = data/inputs/mondoo_input/*/*
methods = GET, POST
